version: "3.3"
services:
  postgres:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env
    volumes:
      - ./tmp:/var/lib/postgresql/data/
  server:
    container_name: "server"
    build: server
    ports:
      - "8888:8888"
  web:
    container_name: "web"
    build: web
    ports:
      - "5001:80"
