version: "3.3"
services:
  postgres:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - ./tmp:/var/lib/postgresql/data/
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  server:
    container_name: "server"
    build: server
    ports:
      - "8888:8888"
  web:
    container_name: "web"
    build: web
    ports:
      - "5001:80"
